### ISSUE TITLE
pyrocksmith error at start

### ISSUE THREAD

**Issue by ciandial** [0x0L/rocksmith#3]
Had a share of problem installing, first had to install Windows 10 Visual C++ Build Tools, then deprecated pycrypto able to be installed only in elevated VS Developer Command Prompt.
pyrocksmith just crashing at start now

C:\Users\tetris4>pyrocksmith --help
Traceback (most recent call last):
  File "C:\Users\tetris4\AppData\Local\Programs\Python\Python36-32\Scripts\pyrocksmith-script.py", line 11, in <module>
    load_entry_point('rocksmith==0.1', 'console_scripts', 'pyrocksmith')()
  File "c:\users\tetris4\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\tetris4\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "c:\users\tetris4\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "c:\users\tetris4\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\tetris4\appdata\local\programs\python\python36-32\lib\site-packages\rocksmith\__init__.py", line 1, in <module>
    from .psarc import PSARC
  File "c:\users\tetris4\appdata\local\programs\python\python36-32\lib\site-packages\rocksmith\psarc.py", line 7, in <module>
    from .crypto import aes_bom, pad, decrypt_psarc, encrypt_psarc
  File "c:\users\tetris4\appdata\local\programs\python\python36-32\lib\site-packages\rocksmith\crypto.py", line 3, in <module>
    from Crypto.Cipher import AES
  File "c:\users\tetris4\appdata\local\programs\python\python36-32\lib\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "c:\users\tetris4\appdata\local\programs\python\python36-32\lib\site-packages\Crypto\Cipher\_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "c:\users\tetris4\appdata\local\programs\python\python36-32\lib\site-packages\Crypto\Util\_raw_api.py", line 34, in <module>
    from Crypto.Util.py3compat import byte_string
ImportError: cannot import name 'byte_string'

**Comment by 0x0L** [comment]
@ciandial 
Thanks for reporting.
I just pushed a commit that should fix this. You must uninstall pycrypto first
